## NLP Phase 1 Text Processing

In [1]:
import numpy as np
import pandas as pd


In [12]:
text="I am feeling very very happy today!!!..."
print("Original text",text)

Original text I am feeling very very happy today!!!...


### Step1

#### convert text into lower case beacause token are consider Happy and happy as differrnt 

In [13]:
text=text.lower()

In [14]:
text

'i am feeling very very happy today!!!...'

### Step 2 Remove punctuation

In [15]:
# using re 
# regular expresion -> 
import re
text=re.sub(r'[^\w\s]','',text)
print("Without Punctuation-> ",text)

Without Punctuation->  i am feeling very very happy today


### Step 3 Tokenization

In [16]:
tokens=text.split()
print("Tokens",tokens)

Tokens ['i', 'am', 'feeling', 'very', 'very', 'happy', 'today']


### Step 4  Stop Words

In [17]:
stopwords=["i","am","is","the","a","an","very"]
filtered_tokens=[]
for word in tokens:
    if word not in stopwords:
        filtered_tokens.append(word)

In [18]:
filtered_tokens

['feeling', 'happy', 'today']

###  Step 5 Stemmanization and Lemmanization

In [19]:
def stem(word):
    if(word.endswith("ing")):
        return word[:-3]
    return word
stemmed_word=[]
for word in filtered_tokens:
    stemmed_word.append(stem(word))

print("After Stemming:",stemmed_word)

After Stemming: ['feel', 'happy', 'today']


## NlP Phase 2-> Words to vector

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
sentences={
    "i am good",
    "i am happy",
    "happy today",
    "i am sad"
}

### Vectorizes

In [27]:

vectorizer=CountVectorizer()
X= vectorizer.fit_transform(sentences)
# learn vocabulory and convert sentence to number

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 5)>

In [29]:
print("Vocabulory:",vectorizer.get_feature_names_out())

Vocabulory: ['am' 'good' 'happy' 'sad' 'today']


In [30]:
print("vectors:")
print(X.toarray())

vectors:
[[1 1 0 0 0]
 [1 0 0 1 0]
 [1 0 1 0 0]
 [0 0 1 0 1]]


In [31]:
# here
# Each row=sentence
# Each col=word


In [33]:
sentences=[
    "I am learninng python and python is good",
    "python is a great programming to learn",
    "i also love ML with python"
]

vectorizer=CountVectorizer()
x=vectorizer.fit_transform(sentences)
print("Vocabulory:",vectorizer.get_feature_names_out())
print("\nMatrix:")
print(x.toarray())

Vocabulory: ['also' 'am' 'and' 'good' 'great' 'is' 'learn' 'learninng' 'love' 'ml'
 'programming' 'python' 'to' 'with']

Matrix:
[[0 1 1 1 0 1 0 1 0 0 0 2 0 0]
 [0 0 0 0 1 1 1 0 0 0 1 1 1 0]
 [1 0 0 0 0 0 0 0 1 1 0 1 0 1]]


### TF IDF


In [34]:
# BAG OF WORDS treat all word equally
# for eg i am learning python, python and python
# It will assign huge weight on python

### What is TF-IDF?
TF stands for Term Frequency and denotes the ratio of number of times a particular word appeared in a Document to total number of words in the document.

   Term Frequency(TF) = [number of times word appeared / total no of words in a document]
Term Frequency values ranges between 0 and 1. If a word occurs more number of times, then it's value will be close to 1.

IDF stands for Inverse Document Frequency and denotes the log of ratio of total number of documents/datapoints in the whole dataset to the number of documents that contains the particular word.

   Inverse Document Frequency(IDF) = [log(Total number of documents / number of documents that contains the word)]
  
In IDF, if a word occured in more number of documents and is common across all documents, then it's value will be less and ratio will approaches to 0.

Finally:

   TF-IDF = Term Frequency(TF) * Inverse Document Frequency(IDF)

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
sentences=[
    "I am learninng python and python is good",
    "python is a great programming to learn",
    "i also love ML with python"
]


In [41]:
vectorizer =TfidfVectorizer()
X=vectorizer.fit_transform(sentences)
# INTERNALLY
# build vocabulary
# calculate TF
# Calculate IDF
# multiply tf * idf
# generate matrix

In [45]:
print(vectorizer.get_feature_names_out())

['also' 'am' 'and' 'good' 'great' 'is' 'learn' 'learninng' 'love' 'ml'
 'programming' 'python' 'to' 'with']


In [46]:
print("TF-IDF matrix")
print(X.toarray())

TF-IDF matrix
[[0.         0.40914568 0.40914568 0.40914568 0.         0.31116583
  0.         0.40914568 0.         0.         0.         0.48329606
  0.         0.        ]
 [0.         0.         0.         0.         0.45050407 0.34261996
  0.45050407 0.         0.         0.         0.45050407 0.26607496
  0.45050407 0.        ]
 [0.47952794 0.         0.         0.         0.         0.
  0.         0.         0.47952794 0.47952794 0.         0.28321692
  0.         0.47952794]]


SyntaxError: unterminated string literal (detected at line 5) (2971776617.py, line 5)