In [40]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [41]:
text=[
    "i am learning deep learning",
    "i like deep learning",
    "deep learning is fun to learn",
    "i also like machine learning"
]

In [42]:
# tokenization
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text)

In [43]:
sequences=tokenizer.texts_to_sequences(text)
print(sequences)

[[2, 5, 1, 3, 1], [2, 4, 3, 1], [3, 1, 6, 7, 8, 9], [2, 10, 4, 11, 1]]


In [44]:
# create input output pair
X=[]
y=[]
for seq in sequences:
    for i in range(1, len(seq)):
        X.append(seq[:i])
        y.append(seq[i])

In [45]:
# PADDING
X= pad_sequences(X)
y=np.array(y)

In [46]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  5]
 [ 0  0  2  5  1]
 [ 0  2  5  1  3]
 [ 0  0  0  0  2]
 [ 0  0  0  2  4]
 [ 0  0  2  4  3]
 [ 0  0  0  0  3]
 [ 0  0  0  3  1]
 [ 0  0  3  1  6]
 [ 0  3  1  6  7]
 [ 3  1  6  7  8]
 [ 0  0  0  0  2]
 [ 0  0  0  2 10]
 [ 0  0  2 10  4]
 [ 0  2 10  4 11]]


In [47]:
print(y)

[ 5  1  3  1  4  3  1  1  6  7  8  9 10  4 11  1]


In [23]:
vocab_size=len(tokenizer.word_index)+1

In [24]:
print(vocab_size)

12


In [25]:
# BUILD RNN MODEL

model=Sequential([
    Embedding(vocab_size,10,input_length=X.shape),
    SimpleRNN(32),
    Dense(vocab_size, activation='softmax')
])

In [26]:
model.compile(loss="sparse_categorical_crossentropy",optimizer="adam")

In [27]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 2.5140
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 2.4932
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 2.4738
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 2.4554
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.4375
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.4196
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 2.4015
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 2.3829
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 2.3636
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 2.3433
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 2.3220
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.2998
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.2767
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.2533
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.2300
Epoch 16/100
1/1 ━━━━

In [34]:
input_text="i am"
seq=tokenizer.texts_to_sequences([input_text])[0]
seq=X = pad_sequences([seq], maxlen=10, padding='post')
pred=model.predict(seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


In [35]:
print(pred)

[[0.0085869  0.03429703 0.0091776  0.06599181 0.0591796  0.0579124
  0.12326153 0.01917077 0.5485352  0.00477497 0.02873188 0.04038024]]


In [36]:
pred_index=np.argmax(pred)

In [37]:
for word, index in tokenizer.word_index.items():
    if index==pred_index:
        print("Next word:",word)

Next word: to
